@description('Short environment name used in resource names.')
param environmentName string

@description('Azure region for all resources.')
param location string

@description('Deterministic suffix generated by the subscription deployment.')
param resourceToken string

@description('SSH public key used by the AKS Linux nodes.')
param sshPublicKey string

@description('AKS system node VM size.')
param nodeVmSize string

@description('Number of AKS system nodes.')
param nodeCount int

@description('Linux administrator username for the AKS nodes.')
param linuxAdminUsername string

@description('Tags applied to deployed resources.')
param tags object

var acrName = take(toLower('acrms${environmentName}${resourceToken}'), 50)
var aksName = take('aks-model-sim-${environmentName}-${resourceToken}', 63)
var workspaceName = take('log-model-sim-${environmentName}-${resourceToken}', 63)
var acrPullRoleDefinitionId = subscriptionResourceId(
  'Microsoft.Authorization/roleDefinitions',
  '7f951dda-4ed3-4680-a7ca-43fe172d538d'
)

resource workspace 'Microsoft.OperationalInsights/workspaces@2025-07-01' = {
  name: workspaceName
  location: location
  tags: tags
  properties: {
    retentionInDays: 30
    sku: {
      name: 'PerGB2018'
    }
  }
}

resource registry 'Microsoft.ContainerRegistry/registries@2025-11-01' = {
  name: acrName
  location: location
  tags: tags
  sku: {
    name: 'Basic'
  }
  properties: {
    adminUserEnabled: false
    anonymousPullEnabled: false
    publicNetworkAccess: 'Enabled'
    zoneRedundancy: 'Disabled'
  }
}

resource cluster 'Microsoft.ContainerService/managedClusters@2025-10-01' = {
  name: aksName
  location: location
  tags: tags
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    dnsPrefix: take('modelsim-${environmentName}-${resourceToken}', 54)
    enableRBAC: true
    disableLocalAccounts: false
    nodeResourceGroup: take('MC_${resourceGroup().name}_${aksName}_${location}', 80)
    agentPoolProfiles: [
      {
        name: 'system'
        count: nodeCount
        vmSize: nodeVmSize
        osType: 'Linux'
        osSKU: 'AzureLinux'
        mode: 'System'
        type: 'VirtualMachineScaleSets'
        enableAutoScaling: false
        enableNodePublicIP: false
        maxPods: 30
      }
    ]
    linuxProfile: {
      adminUsername: linuxAdminUsername
      ssh: {
        publicKeys: [
          {
            keyData: sshPublicKey
          }
        ]
      }
    }
    networkProfile: {
      networkPlugin: 'azure'
      networkPluginMode: 'overlay'
      networkDataplane: 'cilium'
      loadBalancerSku: 'standard'
      outboundType: 'loadBalancer'
      podCidr: '10.244.0.0/16'
      serviceCidr: '10.0.0.0/16'
      dnsServiceIP: '10.0.0.10'
    }
    oidcIssuerProfile: {
      enabled: true
    }
    securityProfile: {
      workloadIdentity: {
        enabled: true
      }
    }
    addonProfiles: {
      omsagent: {
        enabled: true
        config: {
          logAnalyticsWorkspaceResourceID: workspace.id
          useAADAuth: 'true'
        }
      }
    }
  }
}

resource acrPull 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(registry.id, cluster.id, acrPullRoleDefinitionId)
  scope: registry
  properties: {
    principalId: cluster.properties.identityProfile.kubeletidentity.objectId
    principalType: 'ServicePrincipal'
    roleDefinitionId: acrPullRoleDefinitionId
  }
}

output aksClusterName string = cluster.name
output containerRegistryName string = registry.name
output containerRegistryLoginServer string = registry.properties.loginServer
output logAnalyticsWorkspaceName string = workspace.name
